version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "/bindings/panama/"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "/bindings/wasm/"
    schedule:
      interval: "daily"