[build-dependencies]
cbindgen = "0.24.3"

[package]
name = "identification-panama"
version = "0.3.7"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
whichlicense_detection = "2.1.3"
gaoya = "0.1.2"