[build-dependencies]
cbindgen = "0.24.3"

[package]
name = "identification-panama"
version = "0.5.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
whichlicense_detection = "3.0.0"
gaoya = "0.1.2"