#
# Copyright (c) 2023 - for information on the respective copyright owner
# see the NOTICE file and/or the repository https://github.com/whichlicense/libidentification.
#
# SPDX-License-Identifier: Apache-2.0
#
name: Release Lib

on:
  workflow_dispatch:

  push:
    tags:
      - "v*.*.*"

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    strategy:
      fail-fast: false
      matrix:
        target:
          - x86_64-unknown-linux-gnu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build lib for ${{ matrix.target }}
        run: cargo build --release
        working-directory: panama
      - name: Rename x86_64 linux lib
        if: contains(matrix.target, 'x86_64-unknown-linux-gnu')
        run: mv ./target/release/libidentification_panama.so ./libidentification-linux-amd64.so
        working-directory: panama
      - name: Rename aarch64 linux lib
        if: contains(matrix.target, 'aarch64-unknown-linux-gnu')
        run: mv ./target/release/libidentification_panama.so ./libidentification-linux-aarch64.so
        working-directory: panama
      - name: Upload lib artifact
        uses: actions/upload-artifact@v3
        with:
          name: release-${{ github.sha }}
          path: |
            ./panama/libidentification-linux-amd64.so
            ./panama/libidentification-linux-aarch64.so
          if-no-files-found: error
          retention-days: 1
  release:
    needs: [ build ]
    runs-on: ubuntu-latest
    environment: release
    steps:
      - name: Download lib artifacts
        uses: actions/download-artifact@v3
        with:
          name: release-${{ github.sha }}
      - name: Release binary artifacts
        uses: softprops/action-gh-release@v1
        with:
          files: |
            libidentification-linux-amd64.so
            libidentification-linux-aarch64.so