#
# Copyright (c) 2023 - for information on the respective copyright owner
# see the NOTICE file and/or the repository https://github.com/whichlicense/libidentification.
#
# SPDX-License-Identifier: Apache-2.0
#
name: Release Lib

on:
  workflow_dispatch:

  push:
    tags:
      - "v*.*.*"

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  compile:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu, windows, macos ]
    runs-on: ${{ matrix.os }}-latest
    defaults:
      run:
        working-directory: panama
    steps:
      - uses: actions/checkout@v3
      - name: Build lib on ${{ matrix.os }}
        run: cargo build --release
      - name: Rename linux lib
        if: contains(matrix.os, 'ubuntu')
        run: mv ./target/release/libidentification_panama.so ./libidentification-linux-amd64.so
      - name: Rename Windows lib
        if: contains(matrix.os, 'windows')
        run: ls ./target/release
      - name: Rename macOS lib
        if: contains(matrix.os, 'macos')
        run: mv ./target/release/libidentification_panama.dylib ./libidentification-darwin-amd64.dylib
      - name: Upload lib artifact
        uses: actions/upload-artifact@v3
        with:
          name: release-${{ github.sha }}
          path: |
            ./panama/libidentification-linux-amd64.so
            ./panama/libidentification-windows-amd64.dll
            ./panama/libidentification-darwin-amd64.dylib
          if-no-files-found: error
          retention-days: 1
  release:
    needs: [ compile ]
    runs-on: ubuntu-latest
    environment: release
    steps:
      - name: Download lib artifacts
        uses: actions/download-artifact@v3
        with:
          name: release-${{ github.sha }}
      - name: Release binary artifacts
        uses: softprops/action-gh-release@v1
        with:
          files: |
            libidentification-linux-amd64.so
            libidentification-windows-amd64.dll
            libidentification-darwin-amd64.dylib